FROM ubuntu:plucky
MAINTAINER Benedikt Lang <mail@blang.io>
ENV DEBIAN_FRONTEND noninteractive


RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -qy make
RUN apt-get install -qy git
RUN apt-get install -qy texlive-full

#RUN apt-get install -qy python-pygments
RUN apt-get install -qy  gnuplot
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /data
VOLUME ["/data"]
